Bare Metal Forms and Helpers
craigs40/Forms pull request #1
Opened 2021-05-25 23:03 UTC by craigs40

This project includes multiple ways to build a form in rails that can send parameters to a controller so that it can build an instance of a model with those parameters.

2021-05-26 02:21 UTC, BrianSammit reviewed
STATUS INVALID :yellow_circle: 
------------
Friendly reminder: You should make sure that your repo looks professional before review.
Remember that you must have a readme file. Also, check the correct use of Git Flow you are missing the main/master branch. 

Please make these required changes and send it again for another review. 

![tenor (1)](https://user-images.githubusercontent.com/64173189/119593001-1681ff00-bd9f-11eb-8d08-0fd4dd38c903.gif)

2021-05-26 17:19 UTC, taiwo2 requested changes
# STATUS: INVALID 🔴 
@craigs40, your root#index is not available in the controller kindly fix all requirement and push for review  **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/create_new_user.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
![Screenshot 2021-05-26 181224](https://user-images.githubusercontent.com/38242590/119703372-6370de80-be4e-11eb-9b20-7f3da56f39aa.png)

2021-05-28 04:04 UTC, ElijahTobs requested changes
# Status: Changes Required ⚠️ 🚦
## Hi @craigs40  👋
You've done really well so far! 👍 
You've followed the Git flow rules. ✔️ 
You have good commit messages ✔️ 

However, there are some changes that you are required to make before this project can be approved.

## Required Changes ♻️
**Note: This set of changes are marked as Required.**

_See the inline comments below_

## Optional Changes 👌
_Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Check for changes marked as Optional in the inline comments below.


#### If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below

## Happy Coding :computer: 

_Reviewed by_  **Elijah O. Ayandokun**

2021-05-28 04:04 UTC, ElijahTobs commented on README.md
> +# Bare Metal Forms and Helpers
- [x] *[Required]* You should add instructions on how to run your project

2021-05-28 04:04 UTC, ElijahTobs commented on README.md
> +Feel free to check the [issues page](issues/).
- [x] *[Required]* This currently returns a 404 error. Kindly add the right link

2021-05-28 04:04 UTC, ElijahTobs commented on config/routes.rb
> +  resources :users, only: %I[new create edit]
- [x] *[Required]* This should be:
`resources :users, only: [:new, :create, :edit, :update]`

2021-05-28 04:04 UTC, ElijahTobs commented on app/controllers/users_controller.rb
> +
- [x] *[Required]* Your `UsersController` is missing the `update` action

2021-05-28 04:04 UTC, ElijahTobs commented on app/views/users/new.html.erb
> +<form action="/users" method="post" accept-charset="UTF-8">
- [x] *[Required]* This should use `'users_path'` for action instead of `'/users'`

2021-05-28 04:04 UTC, ElijahTobs commented on app/views/users/new.html.erb
> +  <input type="password" id="password" name="password"><br><br>
- [x] *[Required]* This part of the commented out form should use `user[<field_name>]` for **input's name**. For `username`, it will be `user[username]`

2021-05-28 04:04 UTC, ElijahTobs commented on app/views/users/new.html.erb
> +  <%= text_field_tag(:email) %><br><br>
- [x] *[Required]* The `text_field_tag` here should be `email_field_tag`

2021-05-28 04:04 UTC, ElijahTobs commented on app/views/users/new.html.erb
> + <%= form_tag("/users", method: "post") do %>
- [ ] *[Required]* The action here should also be `'users_path'`, not `'/users'`

2021-05-31 18:18 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

### Hi @craigs40! :wave: :wave:

####  Good job for work making all the necessary corrections recommended by the previous reviewer.  👍  Congratulations.  :clap:


#### You may merge, good luck on your next project! :rocket:

If you have any questions pls feel free to drop me a comment.

#### Happy Coding! :+1:

__Robert Loterh __
[GitHub](https://github.com/rloterh) | [LinkedIn](https://www.linkedin.com/in/rloterh/) | [Twitter](https://twitter.com/RLoterh)

2021-06-03 18:29 UTC, merged